role: Agent

service:
  enabled: false

customConfig:
  data_dir: /vector-data-dir

  sources:
    kubernetes_logs:
      type: kubernetes_logs

  sinks:
    loki:
      type: loki
      inputs:
        - kubernetes_logs
      endpoint: http://loki.logging.svc.cluster.local:3100
      encoding:
        codec: json
      labels:
        namespace: "{{`{{ kubernetes.pod_namespace }}`}}"
        pod: "{{`{{ kubernetes.pod_name }}`}}"
        container: "{{`{{ kubernetes.container_name }}`}}"
