apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Nelochka34/k8s-self-managed-platform.git
    targetRevision: main
    path: applications/online-boutique/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true