name: Build and push demo-app image

on:
  push:
    branches:
      - main
    paths:
      - "apps/demo-app/**"
      - ".github/workflows/demo-app-ci.yaml"

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/nelochka34/demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/demo-app
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
